apiVersion: v1
appVersion: 1.2.0
description: A Helm chart for velero
home: https://github.com/vmware-tanzu/velero
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
maintainers:
- email: d-caruso@hotmail.it
  name: domcar
- email: hfernandez@mesosphere.com
  name: hectorj2f
- email: brubakern@vmware.com
  name: nrb
- email: carlisiac@vmware.com
  name: carlisia
- email: ashisham@vmware.com
  name: ashish-amarnath
name: velero
sources:
- https://github.com/vmware-tanzu/velero
tillerVersion: '>=2.10.0'
version: 2.8.1
